### ISSUE TITLE
CMakeList

### ISSUE THREAD

**Issue by MKZwei** [rcliftonharvey/rchoscillators#2]
Hello Clifton,
I wanted to add your oscillator library to my Android studio project. Unfortunately, there is the CMakeLists.txt file missing. I’m kinda of new dealing with C++ and integrating C++ libraries into CMakeList. Could you please give me an advice?

**Comment by rcliftonharvey** [comment]
Hi,
there is no CMakeLists.txt file missing, because this has nothing to do with CMake. No CMake required at all. :)
You add the library folder to your project's library path, you #include the rch_oscillators.h file in your project, that's it.
If your project is managed with CMake, you'll have to create and maintain the CMakeLists.txt file yourself.
https://cmake.org/cmake/help/latest/guide/tutorial/index.html
