### ISSUE TITLE
Passing an oscillator to a skeleton?

### ISSUE THREAD

**Issue by hippyau** [rcliftonharvey/rchoscillators#3]
Say I have 1000 channel elements in a vector,  i'd like each channel to have one assignable type of oscillator (none, sine, saw,  etc...) associated.  Can I assign a oscillator type to an element, rather than each element having a instance of every possible type of oscillator?

**Comment by rcliftonharvey** [comment]
Hm, been a while since I played around with these, let's see if I actually still know anything.

I don't think that would work very easily, no. The problem lies in how the class inheritance is designed and how everything is interconnected.

The `RCH::Helpers::Skeleton` class is a virtual class that really does nothing in and of itself, except for offering all sorts of setter and getter methods and storing a bunch of shared variables for oscillator properties. It's a template or a stencil without much purpose, like (well...) a skeleton, and the main processing function needs to be overridden and implemented by an inheriting class first. 

The setter and getter methods in the Skeleton class are all set to be protected, which means that only inheriting classes can directly access them, but nothing that calls them from outside of the inheriting classes.

The oscillator templates like `RCH::Oscillators::Templates::Sine` inherit from that Skeleton class, they incorporate the setter and getter methods and they hide them away deep down in their private insides. Through instructions like `using Helpers::Skeleton::setSampleRate;` the oscillator template classes can "promote" the setter and getter functions from the private and hidden Skeleton, and advertise them to the outside as publicly accessible methods.

So if you instantiate such a template into a variable, you can e.g. set the template instance's sample rate by calling `variable.setSampleRate(44100.0);` somewhere in your code, this should work for all oscillators equally.

The Skeleton class implements a `setDirection()` method that essentially defines whether a saw oscillator will rise or fall. The saw oscillator has a use for this functionality, so it promotes the hidden function to the outside with a `using Helpers::Skeleton::setDirection;` instruction.

However, a sine oscillator has no use for this functionality, so the sine oscillator does NOT instruct the Skeleton to promote and advertise the `setDirection()` method out.

So like this, an oscillator template can inherit everything inside the Skeleton class and hide it away, and only make the features available to outside that it really needs.

If e.g. the `RCH::Oscillators::Templates::Sine` template inherited from the Skeleton class publicly, `class Sine : public Helpers::Skeleton`, then none of the above would be the case. Every oscillator template class would automatically promote and advertise every Skeleton class to the outside world, so after instantiating e.g. a sine template, you would have direct access to call `sineInstance.setDirection(1.0)` without this actually doing anything.

This is confusing to the user and definitely not desired, and that's why the template classes inherit from Skeleton non-public and only private.

Usually, you would add a private variable somewhere into your channel class `RCH::Helpers::Skeleton osc;` and you would somehow assign it a default oscillator template, either directly or e.g. via a templating argument. Then you'd add a few setter and getter methods, e.g. to select and determine the currently assigned oscillator type, and you'd probably add some sort of setup method that you can call in one go, which passes sample rate, oscillator frequency, etc. on to the oscillator template that's currently assigned to the private variable.

But since all the oscillator template classes only inherit from the Skeleton class privately, the oscillator template classes can't "promote" to the outside that they are in fact inheriting from the Skeleton class. So something outside of an oscillator template class, that checks whether or not an oscillator template class actually "inherits from the Skeleton class", could not succeed. In other words, your channel class could not verify that an oscillator template is actually inheriting from the Skeleton.

I went for this approach, because it allowed me to avoid repetitive code like re-implementing the same `setSampleRate()` and `setFrequency()` methods for eeevery template over and over, and to allow for quick addition of new template oscillators on the fly.

For example: my library currently doesn't have a "none" oscillator you mention. But you could easily add a new "none.h" template file with a `class Sine : private Helpers::Skeleton` that inherits from the Skeleton class, that's it. You could override the `Skeleton::tick()` method to hard-return 0.0, and you could declare which Skeleton methods to advertise to the outside by adding a few setter/getter `using` instructions, if necessary.

This possibility to quickly and easily add new oscillator templates was a fundamental objective of this library.
I know this doesn't solve your problem, but I'm afraid that's how it is.

I mean, you could try setting all the inheritances to public, and setting all the protected variables in the Skeleton to public too, that way you might coax everything into working the way you'd want it to, but I would want to strongly discourage you from doing so. That would not be a clean way to work. :)

What you could do is put in the grunt work and roll your own, it won't be complicated, only tedious and repetitive.

For example, duplicate an oscillator template file, e.g. copy the "library/oscillators/templates/sine.h" template file to "sine2.h". Open the file, rename the class to Sine2 or something more creative, and remove the class inheritance from `RCH::Helpers::Skeleton`.

Then copy & paste all the variables from the Skeleton class "protected" section into the "private" section of the new Sine2 class, and copy & paste the setter/getter implementations from the Skeleton class (just the ones the oscillator template actually "uses") over. Remember to remove any virtual and override qualifiers, and to actually `#include` the new sine2.h in the main `rch_oscillators.h` file.

That should take care of the biggest part. I just ported the sine template for my own local experiments while I was typing this, I'll attach it below and hopefully it'll help you understand what I mean.
[sine2.h.zip](https://github.com/rcliftonharvey/rchoscillators/files/6588231/sine2.h.zip)

The oscillator template now no longer depends on the private Skeleton in its closet. However, it will also not share a common base class with any other oscillator templates that you treated in the same way, so they will all just be unrelated classes. Now you'll need to find a way to "group" them by some sort of shared base class or something again, so that you can store them inside a vector interchangeably.

**Comment by hippyau** [comment]
Wow, thanks for the detailed reply!   I will indeed DIY a class :)  many thanks Rob!
